hugs.settings:
  type: mapping
  label: 'Hug module settings'
  mapping:
    default_count:
      type: integer
      label: 'Default hug count'
    extra_message:
      type: label
      label: 'An additional message to display when hugging'
